[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/buger/goterm"
